global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "ai-module"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "service-a"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "service-b"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "service-c"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
