global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "ai-module"
    metrics_path: /metrics
    static_configs:
      - targets: ["ai-module:8083"]

  - job_name: "service-a"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["service-a:8080"]

  - job_name: "service-b"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["service-b:8081"]

  - job_name: "service-c"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["service-c:8082"]
