version: "3.9"

services:
  loadgen:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      LOADGEN_CONFIG_FILE: /app/configs/loadgen.json
    volumes:
      - ./configs:/app/configs:ro
