spring:
  application:
    name: rps_client

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%level] [%logger{36}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

loadgen:
  tick: 100ms
  log-interval: 10s
  http:
    timeout: 10s
    connect-timeout: 5s
    slow-threshold: 1s
  default-concurrency: 0
