global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "service-a"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["load-generator-service:8080"]

  - job_name: "service-b"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["application-service:8081"]

  - job_name: "service-c"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["rate-limiter-service:8082"]

  - job_name: "ai-module"
    metrics_path: /metrics
    static_configs:
      - targets: ["ai-module:8083"]
